FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    && apt-get clean

COPY requirements.txt .
COPY . .

RUN pip install --no-cache-dir -r requirements.txt

ENV PORT=8000

CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "app:app", "-w", "4", "-b", "0.0.0.0:8000"]

